import { useState } from "react";
import { ACCOUNT_TYPE_META, GENERAL_ACCOUNT_ID, calculateAllAccountBalances, getAccountTotals, isLiabilityAccount } from "../../utils/accounts";
import { validateAccountInput } from "../../utils/accountSchema";
import { formatCurrency } from "../../utils/currency";
import { getFieldErrors } from "../../utils/transactionSchema";
const blank=()=>({name:"",type:"bank",openingBalance:"0",archived:false,createdAt:new Date().toISOString()});
export default function AccountManager({accounts,transactions,transfers,contributions=[],onSave,onArchive}){
 const[open,setOpen]=useState(false),[draft,setDraft]=useState(null),[errors,setErrors]=useState({});const balances=calculateAllAccountBalances(accounts,transactions,transfers,contributions),totals=getAccountTotals(balances);
 const edit=account=>{setDraft({...account,openingBalance:String(account.openingBalance)});setErrors({});};
 const save=event=>{event.preventDefault();const value={...draft,id:draft.id||`account-${crypto.randomUUID()}`,archived:draft.id===GENERAL_ACCOUNT_ID?false:draft.archived};const result=validateAccountInput(value);if(!result.success)return setErrors(getFieldErrors(result.error));onSave(result.data);setDraft(null);};
 return <section className="card mb-4"><div className="card-body"><h3 className="h5 mb-1">Accounts</h3><small className="d-block">Available {formatCurrency(totals.available)} · Total Debt {formatCurrency(totals.totalDebt)}</small><button className="btn btn-outline-primary mt-3" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?"Hide Accounts":"Manage Accounts"}</button>
 {open&&<div className="mt-3"><button className="btn btn-primary mb-3" type="button" onClick={()=>setDraft(blank())}>Add Account</button>
 {draft&&<form className="border rounded p-3 mb-3" onSubmit={save} noValidate><div className="row g-3"><div className="col-12 col-md-4"><label className="form-label" htmlFor="account-name">Account Name</label><input id="account-name" className="form-control" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/>{errors.name&&<div className="text-danger small">{errors.name}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="account-type">Type</label><select id="account-type" className="form-select" value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{Object.entries(ACCOUNT_TYPE_META).map(([id,meta])=><option key={id} value={id}>{meta.label}</option>)}</select></div><div className="col-12 col-md-4"><label className="form-label" htmlFor="opening-balance">Opening Balance</label><input id="opening-balance" type="number" step="any" className="form-control" value={draft.openingBalance} onChange={e=>setDraft({...draft,openingBalance:e.target.value})}/>{errors.openingBalance&&<div className="text-danger small">{errors.openingBalance}</div>}</div></div>{draft.id===GENERAL_ACCOUNT_ID&&<p className="small text-muted mt-2 mb-0">This permanent fallback account cannot be archived or assigned a new ID.</p>}<div className="d-flex gap-2 mt-3"><button className="btn btn-primary">Save Account</button><button type="button" className="btn btn-secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
 <div className="row g-3">{balances.map(({account,balance})=><div className="col-12 col-md-6" key={account.id}><article className="border rounded p-3 h-100"><div className="d-flex justify-content-between gap-2"><div><strong>{ACCOUNT_TYPE_META[account.type].icon} {account.name}</strong><div className="small text-muted">{ACCOUNT_TYPE_META[account.type].label}{account.archived?" · Archived":""}{account.id===GENERAL_ACCOUNT_ID?" · System fallback":""}</div><div>{formatCurrency(balance)}{isLiabilityAccount(account)?" owed":""}</div></div><div className="d-flex flex-column gap-1"><button type="button" className="btn btn-sm btn-outline-primary" onClick={()=>edit(account)}>Edit</button>{account.id!==GENERAL_ACCOUNT_ID&&<button type="button" className="btn btn-sm btn-outline-secondary" onClick={()=>onArchive(account.id,!account.archived)}>{account.archived?"Restore":"Archive"}</button>}</div></div></article></div>)}</div></div>}</div></section>;
}
