import { useState } from "react";
import AccountSelect from "./AccountSelect";
import { calculateAccountBalance, getActiveAccounts, isLiabilityAccount, resolveAccount } from "../../utils/accounts";
import { formatCurrency } from "../../utils/currency";
import { getFieldErrors } from "../../utils/transactionSchema";
import { validateTransferInput } from "../../utils/transferSchema";
import { useAppDialog } from "../ConfirmationModal";

const empty = today => ({ fromAccountId:"general", toAccountId:"", amount:"", date:today, note:"" });
export default function TransferManager({ accounts, transactions, transfers, contributions = [], today, onSave, onDelete }) {
 const {confirm}=useAppDialog();
 const [draft,setDraft]=useState(null), [errors,setErrors]=useState({});
 const save=e=>{e.preventDefault();const value={...draft,id:draft.id||`transfer-${crypto.randomUUID()}`,createdAt:draft.createdAt||new Date().toISOString()};const result=validateTransferInput(value);if(!result.success)return setErrors(getFieldErrors(result.error));onSave(result.data);setDraft(null);setErrors({});};
 const source=draft&&resolveAccount(draft.fromAccountId,accounts), sourceBalance=source?calculateAccountBalance(source,transactions,transfers,contributions):0, amount=Number(draft?.amount);
 return <section className="card mb-4"><div className="card-body"><h3 className="h5 mb-1">Transfers</h3><p className="text-muted mb-0">Move money between accounts and review transfer history.</p><button type="button" className="btn btn-outline-primary mt-3" disabled={getActiveAccounts(accounts).length<2} onClick={()=>setDraft(empty(today))}>Transfer Money</button>
 {draft&&<form onSubmit={save} className="border rounded p-3 my-3" noValidate><div className="row g-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="transfer-from">From</label><AccountSelect id="transfer-from" value={draft.fromAccountId} onChange={v=>setDraft({...draft,fromAccountId:v})} accounts={accounts} includeAccountId={draft.fromAccountId}/></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="transfer-to">To</label><AccountSelect id="transfer-to" value={draft.toAccountId} onChange={v=>setDraft({...draft,toAccountId:v})} accounts={accounts} includeAccountId={draft.toAccountId}/>{errors.toAccountId&&<div className="text-danger small">{errors.toAccountId}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="transfer-amount">Amount</label><input id="transfer-amount" type="number" min="0" step="any" className="form-control" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/>{errors.amount&&<div className="text-danger small">{errors.amount}</div>}{source&&!isLiabilityAccount(source)&&amount>sourceBalance&&<div className="text-warning small">Available: {formatCurrency(sourceBalance)}. This transfer exceeds the available balance.</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="transfer-date">Date</label><input id="transfer-date" type="date" className="form-control" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/>{errors.date&&<div className="text-danger small">{errors.date}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="transfer-note">Note</label><input id="transfer-note" className="form-control" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></div></div><div className="d-flex gap-2 mt-3"><button className="btn btn-primary">Save Transfer</button><button type="button" className="btn btn-secondary" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
 <h4 className="h6 mt-3">Transfer History</h4>{transfers.length?<div className="list-group">{[...transfers].sort((a,b)=>b.date.localeCompare(a.date)).map(item=><div className="list-group-item" key={item.id}><div className="d-flex flex-wrap justify-content-between gap-2"><div><strong>{resolveAccount(item.fromAccountId,accounts).name} → {resolveAccount(item.toAccountId,accounts).name}</strong><div className="small text-muted">{item.date}{item.note?` · ${item.note}`:""}</div></div><div><span className="me-2">{formatCurrency(item.amount)}</span><button type="button" className="btn btn-sm btn-outline-primary me-1" onClick={()=>setDraft({...item,amount:String(item.amount)})}>Edit</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={async()=>{if(await confirm({title:"Delete Transfer?",message:"This transfer will be permanently removed and affected account balances will be recalculated.",confirmLabel:"Delete"}))onDelete(item.id);}}>Delete</button></div></div></div>)}</div>:<p className="text-muted mt-2 mb-0">No transfers recorded.</p>}</div></section>;
}

