import { useEffect, useMemo, useState } from "react";
import { formatCurrency } from "../../utils/currency";
import { EMPTY_VALUE } from "../../utils/display";
import { ACCOUNT_TYPE_META, calculateAccountBalance, getAllAccounts, isLiabilityAccount, resolveAccount } from "../../utils/accounts";
import { getFieldErrors } from "../../utils/transactionSchema";
import { validateSavingsGoalInput } from "../../utils/savingsGoalSchema";
import { validateSavingsGoalContributionInput } from "../../utils/savingsGoalContributionSchema";
import { GOAL_ICONS, getGoalContributions, getGoalProgress, getGoalRemainingAmount, getGoalSavedAmount, getGoalStatus, getGoalsSummary, getTargetDateState } from "../../utils/savingsGoals";
import { estimateGoalCompletionDate } from "../../utils/forecast";
import { useAppDialog } from "../ConfirmationModal";

const formatDate = value => { const [y,m,d]=value.split("-").map(Number); return new Intl.DateTimeFormat("en-MY",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(Date.UTC(y,m-1,d))); };
const newGoal = () => ({ name:"", targetAmount:"", targetDate:"", linkedAccountId:"", icon:GOAL_ICONS[0], note:"", archived:false, createdAt:new Date().toISOString() });
const newContribution = (goalId,today,accountId) => ({ goalId, amount:"", date:today, accountId, note:"", createTransfer:false, createdAt:new Date().toISOString() });

function GoalForm({ initial, accounts, onSave, onCancel, onDelete }) {
 const [draft,setDraft]=useState(initial), [errors,setErrors]=useState({});
 const eligible=getAllAccounts(accounts).filter(account=>!isLiabilityAccount(account)&&(!account.archived||account.id===draft.linkedAccountId));
 const save=e=>{e.preventDefault();const result=validateSavingsGoalInput({...draft,id:draft.id||`goal-${crypto.randomUUID()}`});if(!result.success)return setErrors(getFieldErrors(result.error));onSave(result.data);};
 return <form onSubmit={save} noValidate><div className="row g-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="goal-name">Goal Name</label><input id="goal-name" className="form-control" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/>{errors.name&&<div className="text-danger small">{errors.name}</div>}</div><div className="col-12 col-md-6"><label className="form-label" htmlFor="goal-target">Target Amount</label><input id="goal-target" type="number" min="0" step="any" className="form-control" value={draft.targetAmount} onChange={e=>setDraft({...draft,targetAmount:e.target.value})}/>{errors.targetAmount&&<div className="text-danger small">{errors.targetAmount}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="goal-date">Target Date <span className="text-muted">(optional)</span></label><input id="goal-date" type="date" className="form-control" value={draft.targetDate||""} onChange={e=>setDraft({...draft,targetDate:e.target.value})}/>{errors.targetDate&&<div className="text-danger small">{errors.targetDate}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="goal-account">Linked Account <span className="text-muted">(optional)</span></label><select id="goal-account" className="form-select" value={draft.linkedAccountId||""} onChange={e=>setDraft({...draft,linkedAccountId:e.target.value})}><option value="">No linked account</option>{eligible.map(account=><option key={account.id} value={account.id}>{ACCOUNT_TYPE_META[account.type].icon} {account.name}{account.archived?" (Archived)":""}</option>)}</select></div><div className="col-12 col-md-4"><label className="form-label" htmlFor="goal-icon">Icon</label><select id="goal-icon" className="form-select" value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})}>{GOAL_ICONS.map(icon=><option key={icon} value={icon}>{icon}</option>)}</select></div><div className="col-12"><label className="form-label" htmlFor="goal-note">Note <span className="text-muted">(optional)</span></label><textarea id="goal-note" className="form-control" rows="2" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></div></div><div className="d-flex flex-wrap gap-2 mt-3"><button className="btn btn-primary">Save Goal</button><button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button>{initial.id&&<button type="button" className="btn btn-outline-danger ms-sm-auto" onClick={()=>onDelete(initial)}>Delete Goal</button>}</div></form>;
}

function ContributionForm({ initial, goal, accounts, transfers, transactions, contributions, onSave, onCancel }) {
 const [draft,setDraft]=useState(initial), [errors,setErrors]=useState({});
 const options=getAllAccounts(accounts).filter(account=>!isLiabilityAccount(account)&&(!account.archived||account.id===draft.accountId));
 const linkedTransfer=draft.transferId?transfers.find(item=>item.id===draft.transferId):null;
 const source=resolveAccount(draft.accountId,accounts); const balance=calculateAccountBalance(source,transactions,transfers,contributions); const amount=Number(draft.amount);
 const canTransfer=goal.linkedAccountId&&goal.linkedAccountId!==draft.accountId;
 const save=e=>{e.preventDefault();const data={...draft,id:draft.id||`goal-contribution-${crypto.randomUUID()}`,transferId:draft.createTransfer?(draft.transferId||`transfer-${crypto.randomUUID()}`):draft.transferId};const result=validateSavingsGoalContributionInput(data);if(!result.success)return setErrors(getFieldErrors(result.error));const transfer=draft.createTransfer?{id:result.data.transferId,fromAccountId:result.data.accountId,toAccountId:goal.linkedAccountId,amount:result.data.amount,date:result.data.date,note:`Savings goal: ${goal.name}`,createdAt:linkedTransfer?.createdAt||new Date().toISOString()}:null;onSave(result.data,transfer);};
 return <form onSubmit={save} noValidate><h4 className="h5">{draft.id?"Edit":"Add"} Contribution</h4><div className="row g-3"><div className="col-12 col-md-4"><label className="form-label" htmlFor="contribution-amount">Amount</label><input id="contribution-amount" type="number" min="0" step="any" className="form-control" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})} autoFocus/>{errors.amount&&<div className="text-danger small">{errors.amount}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="contribution-date">Date</label><input id="contribution-date" type="date" className="form-control" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/>{errors.date&&<div className="text-danger small">{errors.date}</div>}</div><div className="col-12 col-md-4"><label className="form-label" htmlFor="contribution-account">Account</label><select id="contribution-account" className="form-select" value={draft.accountId} onChange={e=>setDraft({...draft,accountId:e.target.value,createTransfer:false})}>{options.map(account=><option key={account.id} value={account.id}>{account.name}{account.archived?" (Archived)":""}</option>)}</select></div><div className="col-12"><label className="form-label" htmlFor="contribution-note">Note</label><input id="contribution-note" className="form-control" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></div>{canTransfer&&<div className="col-12"><div className="form-check"><input id="contribution-transfer" className="form-check-input" type="checkbox" checked={Boolean(draft.createTransfer)} onChange={e=>setDraft({...draft,createTransfer:e.target.checked})}/><label className="form-check-label" htmlFor="contribution-transfer">Create transfer to {resolveAccount(goal.linkedAccountId,accounts).name}</label></div>{draft.createTransfer&&amount>balance&&<div className="text-warning small">Available: {formatCurrency(balance)}. This transfer exceeds the available balance.</div>}</div>}</div><div className="d-flex gap-2 mt-3"><button className="btn btn-primary">Save Contribution</button><button type="button" className="btn btn-secondary" onClick={onCancel}>Cancel</button></div></form>;
}

export default function SavingsGoalsDashboard({ goals, contributions, accounts, transfers, transactions, today, recurringGoalRules = [], onSaveGoal, onArchiveGoal, onDeleteGoal, onSaveContribution, onDeleteContribution }) {
 const {confirm}=useAppDialog();
 const [filter,setFilter]=useState("active"), [search,setSearch]=useState(""), [editor,setEditor]=useState(null), [selectedId,setSelectedId]=useState(null), [contributionDraft,setContributionDraft]=useState(null);
 useEffect(()=>{const close=event=>{if(event.key!=="Escape")return;setEditor(null);setSelectedId(null);setContributionDraft(null);};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[]);
 const summary=getGoalsSummary(goals,contributions), selected=goals.find(goal=>goal.id===selectedId);
 const shown=useMemo(()=>goals.filter(goal=>{const status=getGoalStatus(goal,contributions);if(filter==="active"&&goal.archived)return false;if(filter==="completed"&&status!=="Completed")return false;if(filter==="archived"&&!goal.archived)return false;return goal.name.toLowerCase().includes(search.trim().toLowerCase());}).sort((a,b)=>{const ac=getGoalStatus(a,contributions)==="Completed",bc=getGoalStatus(b,contributions)==="Completed";return Number(ac)-Number(bc)||(a.targetDate||"9999").localeCompare(b.targetDate||"9999")||a.name.localeCompare(b.name);}),[goals,contributions,filter,search]);
 const openContribution=(goal,item)=>{const fallback=getAllAccounts(accounts).find(account=>!isLiabilityAccount(account)&&!account.archived)?.id||"general";const transfer=item?.transferId?transfers.find(value=>value.id===item.transferId):null;setSelectedId(null);setContributionDraft(item?{...item,amount:String(item.amount),createTransfer:Boolean(transfer&&goal.linkedAccountId),accountId:transfer?.fromAccountId||item.accountId}:newContribution(goal.id,today,fallback));};
 const deleteGoal=async goal=>{if(!await confirm({title:"Delete Savings Goal?",message:`Permanently delete “${goal.name}”? Its savings contributions and recurring contribution rules will also be deleted. Linked transfers will remain in account history.`,confirmLabel:"Delete Goal"}))return;onDeleteGoal(goal.id);setEditor(null);setSelectedId(null);setContributionDraft(null);};
 const renderProgress=goal=>{const saved=getGoalSavedAmount(goal.id,contributions),progress=getGoalProgress(goal,contributions),remaining=getGoalRemainingAmount(goal,contributions),status=getGoalStatus(goal,contributions),eta=estimateGoalCompletionDate(goal,contributions,recurringGoalRules.filter(rule=>rule.goalId===goal.id),today);const etaText=eta.status==="estimated"?formatDate(eta.date):eta.status==="completed"?"Completed":eta.status==="beyond"?"More than 30 years":"No recurring contribution scheduled";return <><div className="d-flex justify-content-between gap-2"><strong>{formatCurrency(saved)} / {formatCurrency(goal.targetAmount)}</strong><span>{progress.toFixed(1)}%</span></div><div className="progress my-2" role="progressbar" aria-label={`${goal.name} progress`} aria-valuenow={Math.round(progress)} aria-valuemin="0" aria-valuemax="100"><div className={`progress-bar${status==="Completed"?" bg-success":""}`} style={{width:`${Math.min(100,progress)}%`}}/></div><div className="small">{saved>goal.targetAmount?`Exceeded by ${formatCurrency(saved-goal.targetAmount)}`:`${formatCurrency(remaining)} remaining`} · {status}</div>{!goal.archived&&<div className="small text-muted">Estimated completion: {etaText}</div>}</>;};
 return <section aria-labelledby="savings-goals-heading"><div className="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h2 id="savings-goals-heading" className="h4 mb-1">Savings Goals</h2><p className="text-muted mb-0">Allocate savings without changing income or expenses.</p></div><button type="button" className="btn btn-primary" onClick={()=>setEditor(newGoal())}>Create Goal</button></div>
 <div className="row g-3 mb-4">{[["Total Saved",formatCurrency(summary.totalSaved)],["Total Target",formatCurrency(summary.totalTarget)],["Overall Progress",summary.progress===null?EMPTY_VALUE:`${summary.progress.toFixed(1)}%`],["Active Goals",summary.activeCount]].map(([label,value])=><div className="col-6 col-lg-3" key={label}><div className="card h-100"><div className="card-body"><span className="small text-muted">{label}</span><div className="h5 mb-0">{value}</div></div></div></div>)}</div>
 <div className="row g-2 mb-3"><div className="col-12 col-sm"><label className="form-label" htmlFor="goal-search">Search goals</label><input id="goal-search" type="search" className="form-control" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="col-12 col-sm-auto"><label className="form-label" htmlFor="goal-filter">Status</label><select id="goal-filter" className="form-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="completed">Completed</option><option value="archived">Archived</option><option value="all">All</option></select></div></div>
 {!shown.length?<div className="text-center border rounded p-4"><p className="mb-2">No savings goals found.</p><button type="button" className="btn btn-outline-primary" onClick={()=>setEditor(newGoal())}>Create a goal</button></div>:<div className="row g-3">{shown.map(goal=><div className="col-12 col-md-6" key={goal.id}><article className="card h-100 shadow-sm"><div className="card-body"><h3 className="h5">{goal.icon} {goal.name}</h3>{renderProgress(goal)}{goal.targetDate&&<div className="small mt-2">Target: {formatDate(goal.targetDate)} · {getTargetDateState(goal,today)}</div>}{goal.linkedAccountId&&<div className="small text-muted">{resolveAccount(goal.linkedAccountId,accounts).name}</div>}<div className="d-flex flex-wrap gap-2 mt-3"><button type="button" className="btn btn-sm btn-primary" onClick={()=>openContribution(goal)}>Add Contribution</button><button type="button" className="btn btn-sm btn-outline-primary" onClick={()=>setSelectedId(goal.id)}>View Details</button><button type="button" className="btn btn-sm btn-outline-secondary" onClick={()=>setEditor({...goal,targetAmount:String(goal.targetAmount),targetDate:goal.targetDate||"",linkedAccountId:goal.linkedAccountId||""})}>Edit</button><button type="button" className="btn btn-sm btn-outline-secondary" onClick={async()=>{const action=goal.archived?"Restore":"Archive";if(await confirm({title:`${action} Savings Goal?`,message:`${action} “${goal.name}”? Contributions and transfers will be preserved.${goal.archived?"":" Recurring contributions will be paused."}`,confirmLabel:action}))onArchiveGoal(goal.id,!goal.archived);}}>{goal.archived?"Restore":"Archive"}</button></div></div></article></div>)}</div>}
 {editor&&<div className="planner-settings-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setEditor(null)}><section className="card shadow planner-settings" role="dialog" aria-modal="true" aria-labelledby="goal-form-heading"><div className="card-body"><h3 id="goal-form-heading" className="h4">{editor.id?"Edit":"Create"} Savings Goal</h3><GoalForm initial={editor} accounts={accounts} onSave={goal=>{onSaveGoal(goal);setEditor(null);}} onCancel={()=>setEditor(null)} onDelete={deleteGoal}/></div></section></div>}
 {contributionDraft&&<div className="planner-settings-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setContributionDraft(null)}><section className="card shadow planner-settings" role="dialog" aria-modal="true" aria-labelledby="contribution-heading"><div className="card-body"><h3 id="contribution-heading" className="h4">{goals.find(goal=>goal.id===contributionDraft.goalId)?.icon} {goals.find(goal=>goal.id===contributionDraft.goalId)?.name}</h3><ContributionForm initial={contributionDraft} goal={goals.find(goal=>goal.id===contributionDraft.goalId)} accounts={accounts} transfers={transfers} transactions={transactions} contributions={contributions} onSave={(item,transfer)=>{onSaveContribution(item,transfer);setContributionDraft(null);}} onCancel={()=>setContributionDraft(null)}/></div></section></div>}
 {selected&&<div className="planner-settings-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setSelectedId(null)}><section className="card shadow planner-settings" role="dialog" aria-modal="true" aria-labelledby="goal-details-heading"><div className="card-body"><div className="d-flex justify-content-between"><h3 id="goal-details-heading" className="h4">{selected.icon} {selected.name}</h3><button type="button" className="btn-close" aria-label="Close goal details" onClick={()=>setSelectedId(null)}/></div>{renderProgress(selected)}{selected.note&&<p className="mt-3">{selected.note}</p>}<h4 className="h5 mt-4">Contribution History</h4>{getGoalContributions(selected.id,contributions).length?<div className="list-group">{[...getGoalContributions(selected.id,contributions)].sort((a,b)=>b.date.localeCompare(a.date)).map(item=>{const linked=item.transferId?transfers.find(value=>value.id===item.transferId):null;return <div className="list-group-item" key={item.id}><div className="d-flex flex-wrap justify-content-between gap-2"><div><strong>{formatCurrency(item.amount)}</strong><div className="small text-muted">{formatDate(item.date)} · {resolveAccount(item.accountId,accounts).name}</div>{linked?<div className="small">Transfer: {resolveAccount(linked.fromAccountId,accounts).name} → {resolveAccount(linked.toAccountId,accounts).name}</div>:item.transferId?<div className="small text-warning">Linked transfer no longer available</div>:null}{item.note&&<div className="small">{item.note}</div>}</div><div><button type="button" className="btn btn-sm btn-outline-primary me-1" onClick={()=>openContribution(selected,item)}>Edit</button><button type="button" className="btn btn-sm btn-outline-danger" onClick={async()=>{if(await confirm({title:"Delete Contribution?",message:"This savings contribution will be removed. Any linked transfer will remain in account history.",confirmLabel:"Delete"}))onDeleteContribution(item.id);}}>Delete</button></div></div></div>})}</div>:<p className="text-muted">No contributions yet.</p>}<div className="d-flex flex-wrap gap-2 mt-3"><button type="button" className="btn btn-primary" onClick={()=>openContribution(selected)}>Add Contribution</button><button type="button" className="btn btn-outline-danger ms-sm-auto" onClick={()=>deleteGoal(selected)}>Delete Goal</button></div></div></section></div>}
 </section>;
}

