import { useState } from "react";
import { formatCurrency } from "../../utils/currency";
import { getAccountDisplayName, getActiveAccounts, isLiabilityAccount } from "../../utils/accounts";
import { getNextOccurrence } from "../../utils/recurring";
import { getFieldErrors } from "../../utils/transactionSchema";
import { validateRecurringGoalContributionInput, validateRecurringTransferInput } from "../../utils/recurringMoneySchema";
import { useAppDialog } from "../ConfirmationModal";

const schedule=today=>({amount:"",frequency:"monthly",interval:"1",startDate:today,endDate:"",note:"",active:true,processedThrough:null,pausedAt:null,createdAt:new Date().toISOString()});
const Fields=({draft,setDraft,errors})=><div className="row g-3"><div className="col-6 col-md-3"><label className="form-label" htmlFor="money-amount">Amount</label><input id="money-amount" type="number" min="0" step="any" className="form-control" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/>{errors.amount&&<div className="text-danger small">{errors.amount}</div>}</div><div className="col-6 col-md-3"><label className="form-label" htmlFor="money-frequency">Frequency</label><select id="money-frequency" className="form-select" value={draft.frequency} onChange={e=>setDraft({...draft,frequency:e.target.value})}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></div><div className="col-6 col-md-3"><label className="form-label" htmlFor="money-interval">Every</label><input id="money-interval" type="number" min="1" className="form-control" value={draft.interval} onChange={e=>setDraft({...draft,interval:e.target.value})}/></div><div className="col-6 col-md-3"><label className="form-label" htmlFor="money-start">Start Date</label><input id="money-start" type="date" className="form-control" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></div><div className="col-12 col-md-4"><label className="form-label" htmlFor="money-end">End Date <span className="text-muted">(optional)</span></label><input id="money-end" type="date" className="form-control" value={draft.endDate||""} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></div><div className="col-12 col-md-8"><label className="form-label" htmlFor="money-note">Note</label><input id="money-note" className="form-control" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></div></div>;

export default function RecurringMoneyManager({transferRules,goalRules,accounts,goals,contributions,today,onSaveTransfer,onToggleTransfer,onDeleteTransfer,onSaveGoal,onToggleGoal,onDeleteGoal,embedded=false}){
 const {confirm}=useAppDialog();
 const [kind,setKind]=useState(null),[draft,setDraft]=useState(null),[errors,setErrors]=useState({});const activeAccounts=getActiveAccounts(accounts),hasGoals=goals.length>0;
 const beginTransfer=rule=>{setKind("transfer");setDraft(rule?{...rule,amount:String(rule.amount),interval:String(rule.interval),endDate:rule.endDate||""}:{...schedule(today),fromAccountId:activeAccounts[0]?.id||"general",toAccountId:activeAccounts[1]?.id||"general"});setErrors({});};
 const beginGoal=rule=>{setKind("goal");setDraft(rule?{...rule,amount:String(rule.amount),interval:String(rule.interval),endDate:rule.endDate||""}:{...schedule(today),goalId:goals.find(item=>!item.archived)?.id||"",accountId:activeAccounts.find(item=>!isLiabilityAccount(item))?.id||"general",createTransfer:false});setErrors({});};
 const save=e=>{e.preventDefault();const value={...draft,id:draft.id||(kind==="transfer"?`recurring-transfer-${crypto.randomUUID()}`:`recurring-goal-contribution-${crypto.randomUUID()}`)};const result=kind==="transfer"?validateRecurringTransferInput(value):validateRecurringGoalContributionInput(value);if(!result.success)return setErrors(getFieldErrors(result.error));(kind==="transfer"?onSaveTransfer:onSaveGoal)(result.data,Boolean(draft.id));setKind(null);setDraft(null);};
 const ruleRow=(rule,type)=>{const goal=type==="goal"?goals.find(item=>item.id===rule.goalId):null,next=getNextOccurrence(rule,today),completed=goal&&contributions.filter(item=>item.goalId===goal.id).reduce((sum,item)=>sum+item.amount,0)>=goal.targetAmount;return <div className="list-group-item" key={rule.id}><div className="d-flex flex-wrap justify-content-between gap-2"><div><strong>{type==="transfer"?`${getAccountDisplayName(rule.fromAccountId,accounts)} → ${getAccountDisplayName(rule.toAccountId,accounts)}`:goal?`${goal.icon} ${goal.name}`:"Missing goal"}</strong> · {formatCurrency(rule.amount)}<div className="small text-muted">Every {rule.interval>1?`${rule.interval} `:""}{rule.frequency} · {rule.active?(next?`Next: ${next}`:"Ended"):"Paused"}</div>{goal?.archived&&<div className="small text-warning">Goal archived — generation suspended</div>}{completed&&rule.active&&<div className="small text-warning">Goal completed — recurring contribution still active</div>}</div><div className="d-flex gap-1"><button className="btn btn-sm btn-outline-primary" type="button" onClick={()=>type==="transfer"?beginTransfer(rule):beginGoal(rule)}>Edit</button><button className="btn btn-sm btn-outline-secondary" type="button" onClick={()=>type==="transfer"?onToggleTransfer(rule.id):onToggleGoal(rule.id)}>{rule.active?"Pause":"Resume"}</button><button className="btn btn-sm btn-outline-danger" type="button" onClick={async()=>{const label=type==="transfer"?"Recurring Transfer":"Recurring Savings Contribution";if(await confirm({title:`Delete ${label}?`,message:"Future activity from this rule will stop. Existing generated history will remain.",confirmLabel:"Delete"}))(type==="transfer"?onDeleteTransfer:onDeleteGoal)(rule.id);}}>Delete</button></div></div></div>;};
 return <section className={embedded?"":"card mt-4"}><div className={embedded?"":"card-body"}><h2 className="h4">Money Movement</h2><div className="row g-4"><div className="col-12"><div className="d-flex justify-content-between"><h3 className="h5">Recurring Transfers</h3><button type="button" className="btn btn-sm btn-outline-primary" onClick={()=>beginTransfer()}>Add</button></div><div className="list-group">{transferRules.length?transferRules.map(rule=>ruleRow(rule,"transfer")):<p className="text-muted">No recurring transfers.</p>}</div></div>{hasGoals&&<div className="col-12"><div className="d-flex justify-content-between"><h3 className="h5">Recurring Savings Contributions</h3><button type="button" className="btn btn-sm btn-outline-primary" disabled={!goals.some(goal=>!goal.archived)} onClick={()=>beginGoal()}>Add</button></div><div className="list-group">{goalRules.length?goalRules.map(rule=>ruleRow(rule,"goal")):<p className="text-muted">No recurring savings contributions.</p>}</div></div>}</div>
 {draft&&(kind!=="goal"||goals.some(goal=>goal.id===draft.goalId))&&<form className="border rounded p-3 mt-3" onSubmit={save}><h3 className="h5">{draft.id?"Edit":"New"} recurring {kind}</h3>{kind==="transfer"?<div className="row g-3 mb-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="rec-from">From</label><select id="rec-from" className="form-select" value={draft.fromAccountId} onChange={e=>setDraft({...draft,fromAccountId:e.target.value})}>{activeAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="rec-to">To</label><select id="rec-to" className="form-select" value={draft.toAccountId} onChange={e=>setDraft({...draft,toAccountId:e.target.value})}>{activeAccounts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>{errors.toAccountId&&<div className="text-danger small">{errors.toAccountId}</div>}</div></div>:<div className="row g-3 mb-3"><div className="col-12 col-md-6"><label className="form-label" htmlFor="rec-goal">Goal</label><select id="rec-goal" className="form-select" value={draft.goalId} onChange={e=>setDraft({...draft,goalId:e.target.value})}>{goals.filter(item=>!item.archived||item.id===draft.goalId).map(item=><option key={item.id} value={item.id}>{item.icon} {item.name}</option>)}</select></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="rec-goal-account">From Account</label><select id="rec-goal-account" className="form-select" value={draft.accountId} onChange={e=>setDraft({...draft,accountId:e.target.value})}>{activeAccounts.filter(item=>!isLiabilityAccount(item)).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="col-12"><div className="form-check"><input id="rec-goal-transfer" type="checkbox" className="form-check-input" checked={draft.createTransfer} onChange={e=>setDraft({...draft,createTransfer:e.target.checked})}/><label htmlFor="rec-goal-transfer" className="form-check-label">Create transfer to the goal&apos;s linked account when available</label></div></div></div>}<Fields draft={draft} setDraft={setDraft} errors={errors}/><div className="d-flex gap-2 mt-3"><button className="btn btn-primary">Save Rule</button><button className="btn btn-secondary" type="button" onClick={()=>{setDraft(null);setKind(null);}}>Cancel</button></div></form>}</div></section>;
}

