import { useEffect, useState } from "react";
import { formatCurrency } from "../utils/currency";
import { buildCalendarMonth, formatMonth, shiftMonth } from "../utils/dashboard";
import { getToday } from "../utils/recurring";
import CategoryLabel from "./categories/CategoryIcon";
import { getAccountDisplayName } from "../utils/accounts";
import PeriodNavigator from "./PeriodNavigator";
import { MIDDLE_DOT, MINUS_SIGN, RIGHT_ARROW, SAVINGS_ALLOCATION_SYMBOL, TRANSFER_SYMBOL } from "../utils/display";

const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const formatDate = value => { const [year,month,day]=value.split("-").map(Number); return new Intl.DateTimeFormat("en-MY",{dateStyle:"long",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,day))); };

export default function FinanceCalendar({ transactions, transfers = [], accounts = [], customCategories = [], savingsGoals = [], savingsGoalContributions = [] }) {
 const today=getToday(), currentMonth=today.slice(0,7); const [selectedMonth,setSelectedMonth]=useState(currentMonth), [selectedDate,setSelectedDate]=useState(null);
 const calendar=buildCalendarMonth(transactions,selectedMonth,transfers,savingsGoalContributions);
 const selected=selectedDate?(calendar.byDate.get(selectedDate)||{income:0,expenses:0,transactions:[],transfers:[],savingsGoalContributions:[]}):null;
 useEffect(()=>{if(!selectedDate)return;const close=e=>{if(e.key==="Escape")setSelectedDate(null);};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[selectedDate]);
 const chooseDay=day=>{if(day.outside)setSelectedMonth(day.date.slice(0,7));setSelectedDate(day.date);};
 return <section aria-labelledby="calendar-heading"><div className="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><div><h2 id="calendar-heading" className="h4 mb-1">Finance Calendar</h2><p className="small text-muted mb-0">Daily transactions, transfers, and savings activity.</p></div></div>
 <PeriodNavigator mode="month" label={formatMonth(selectedMonth)} dateTime={selectedMonth} isCurrent={selectedMonth===currentMonth} onPrevious={()=>setSelectedMonth(month=>shiftMonth(month,-1))} onCurrent={()=>setSelectedMonth(currentMonth)} onNext={()=>setSelectedMonth(month=>shiftMonth(month,1))}/>
 <div className="row g-2 mb-3">{[["Income",calendar.summary.income],["Expenses",calendar.summary.expenses],["Net",calendar.summary.net],["Transactions",calendar.summary.count]].map(([label,value])=><div className="col-6 col-lg-3" key={label}><div className="card h-100"><div className="card-body p-2 p-sm-3"><div className="small text-muted">{label}</div><strong>{label==="Transactions"?value:formatCurrency(value)}</strong></div></div></div>)}</div>
 <div className="d-flex flex-wrap gap-3 small mb-2" aria-label="Calendar legend"><span>+ Income</span><span>{MINUS_SIGN} Expenses</span><span>{TRANSFER_SYMBOL} Transfers</span><span>{SAVINGS_ALLOCATION_SYMBOL} Savings allocations</span></div>
 <div className="finance-calendar" role="grid" aria-label={`Financial activity for ${formatMonth(selectedMonth)}`}>{weekdays.map(day=><div className="finance-calendar-weekday" role="columnheader" key={day}>{day}</div>)}{calendar.days.map(day=><button type="button" role="gridcell" key={day.date} className={`finance-calendar-day${day.outside?" outside":""}${day.date===today?" today":""}${day.count||day.transfers.length||day.savingsGoalContributions.length?" has-activity":""}`} onClick={()=>chooseDay(day)} aria-label={`${formatDate(day.date)}. Income ${formatCurrency(day.income)}. Expenses ${formatCurrency(day.expenses)}. ${day.count} transactions. ${day.transfers.length} transfers. ${day.savingsGoalContributions.length} savings contributions.`}><span className="finance-calendar-number">{day.day}{day.date===today&&<span className="visually-hidden"> Today</span>}</span>{day.income>0&&<span className="finance-calendar-amount income">+ {formatCurrency(day.income)}</span>}{day.expenses>0&&<span className="finance-calendar-amount expense">{MINUS_SIGN} {formatCurrency(day.expenses)}</span>}{day.count>0&&<span className="finance-calendar-count">{day.count} tx</span>}{day.transfers.length>0&&<span className="finance-calendar-count">{TRANSFER_SYMBOL} {day.transfers.length} transfer{day.transfers.length===1?"":"s"}</span>}{day.savingsGoalContributions.length>0&&<span className="finance-calendar-count">{SAVINGS_ALLOCATION_SYMBOL} {formatCurrency(day.savingsGoalContributions.reduce((sum,item)=>sum+item.amount,0))} saved</span>}</button>)}</div>
 {selectedDate&&<div className="planner-settings-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&setSelectedDate(null)}><section className="card shadow planner-settings" role="dialog" aria-modal="true" aria-labelledby="day-detail-heading"><div className="card-body"><div className="d-flex justify-content-between gap-2"><h3 id="day-detail-heading" className="h4">{formatDate(selectedDate)}</h3><button type="button" className="btn-close" aria-label="Close day details" onClick={()=>setSelectedDate(null)}/></div><dl className="row"><dt className="col-6">Income</dt><dd className="col-6 text-end">{formatCurrency(selected.income)}</dd><dt className="col-6">Expenses</dt><dd className="col-6 text-end">{formatCurrency(selected.expenses)}</dd><dt className="col-6">Net</dt><dd className="col-6 text-end">{formatCurrency(selected.income-selected.expenses)}</dd></dl>
 <h4 className="h5">Transactions</h4>{selected.transactions.length?<ul className="list-group list-group-flush">{selected.transactions.map(item=><li className="list-group-item px-0 d-flex justify-content-between gap-2" key={item.id}><div><strong>{item.description}</strong><div className="small text-muted d-flex flex-wrap align-items-center gap-1"><CategoryLabel tag={item.tag} customCategories={customCategories} size={18} /><span>{MIDDLE_DOT} {getAccountDisplayName(item.accountId,accounts)} {MIDDLE_DOT} {item.type}{item.recurringRuleId?`${MIDDLE_DOT} Recurring`:""}</span></div></div><span>{item.type==="income"?"+":MINUS_SIGN}{formatCurrency(item.amount)}</span></li>)}</ul>:<p className="text-muted">No transactions on this date.</p>}
 <h4 className="h5 mt-3">{TRANSFER_SYMBOL} Transfers</h4>{selected.transfers.length?<ul className="list-group list-group-flush">{selected.transfers.map(item=><li className="list-group-item px-0 d-flex justify-content-between gap-2" key={item.id}><span>{TRANSFER_SYMBOL} {getAccountDisplayName(item.fromAccountId,accounts)} {RIGHT_ARROW} {getAccountDisplayName(item.toAccountId,accounts)}</span><span>{formatCurrency(item.amount)}</span></li>)}</ul>:<p className="text-muted">No transfers on this date.</p>}
 <h4 className="h5 mt-3">{SAVINGS_ALLOCATION_SYMBOL} Savings Goals</h4>{selected.savingsGoalContributions.length?<ul className="list-group list-group-flush">{selected.savingsGoalContributions.map(item=>{const goal=savingsGoals.find(value=>value.id===item.goalId), linked=item.transferId?transfers.find(value=>value.id===item.transferId):null;return <li className="list-group-item px-0 d-flex justify-content-between gap-2" key={item.id}><div><strong>{SAVINGS_ALLOCATION_SYMBOL} {goal?`${goal.icon} ${goal.name}`:"Missing savings goal"}</strong><div className="small text-muted">{getAccountDisplayName(item.accountId,accounts)}</div>{linked&&<div className="small text-muted">Allocation linked to {getAccountDisplayName(linked.fromAccountId,accounts)} {RIGHT_ARROW} {getAccountDisplayName(linked.toAccountId,accounts)}</div>}</div><span>{MINUS_SIGN}{formatCurrency(item.amount)}</span></li>;})}</ul>:<p className="text-muted">No savings contributions on this date.</p>}
 <button type="button" className="btn btn-secondary mt-3" onClick={()=>setSelectedDate(null)}>Close</button></div></section></div>}</section>;
}

