import Papa from "papaparse";
import { escapeSpreadsheetCell, normalizeCsvHeader } from "./csv.js";
import { getAccountDisplayName, getAllAccounts } from "./accounts.js";
import { validateTransferInput } from "./transferSchema.js";
import { validateAccountInput } from "./accountSchema.js";
import { validateCustomCategory } from "./customCategorySchema.js";
import { validateSavingsGoalInput } from "./savingsGoalSchema.js";
import { validateSavingsGoalContributionInput } from "./savingsGoalContributionSchema.js";
import { categories as builtInCategories, mainCategories } from "./tags.js";
import { GOAL_ICONS } from "./savingsGoals.js";

const csv=rows=>`\uFEFF${Papa.unparse(rows,{newline:"\r\n"})}`;
const safe=value=>escapeSpreadsheetCell(value);
export const createTransferCsv=(items,accounts)=>csv(items.map(item=>({"From Account":safe(getAccountDisplayName(item.fromAccountId,accounts)),"To Account":safe(getAccountDisplayName(item.toAccountId,accounts)),Amount:item.amount,Date:item.date,Note:safe(item.note)})));
export const createAccountCsv=items=>csv(items.map(item=>({Name:safe(item.name),Type:item.type,"Opening Balance":item.openingBalance,Archived:item.archived})));
export const createCustomCategoryCsv=items=>csv(items.map(item=>({Name:safe(item.name),Type:item.type,"Main Category":safe(mainCategories.find(main=>main.id===(item.mainCategoryId||"other"))?.name||"Other"),"Icon Type":item.iconType||"emoji",Icon:safe(item.icon),"Image Data":item.imageData||"",Keywords:safe(item.keywords.join("; ")),"50/30/20 Classification":item.budgetGroup??"",Archived:item.archived})));
export const createSavingsGoalCsv=(items,accounts)=>csv(items.map(item=>({Name:safe(item.name),"Target Amount":item.targetAmount,"Target Date":item.targetDate??"","Linked Account":item.linkedAccountId?safe(getAccountDisplayName(item.linkedAccountId,accounts)):"",Icon:safe(item.icon),Note:safe(item.note),Archived:item.archived})));
export const createGoalContributionCsv=(items,goals,accounts)=>csv(items.map(item=>({Goal:safe(goals.find(goal=>goal.id===item.goalId)?.name??"Missing goal"),Amount:item.amount,Date:item.date,Account:safe(getAccountDisplayName(item.accountId,accounts)),"Transfer Reference":item.transferId??"",Note:safe(item.note)})));
const boolean=value=>String(value).trim().toLowerCase()==="true";
const parse=(text,required,convert)=>{if(!String(text).trim())return{error:"The CSV file is empty.",rows:0,valid:[],invalid:[]};const parsed=Papa.parse(text,{header:true,skipEmptyLines:"greedy",transformHeader:normalizeCsvHeader});const fields=parsed.meta.fields??[],missing=required.filter(field=>!fields.includes(field));if(missing.length)return{error:`Missing required column${missing.length===1?"":"s"}: ${missing.join(", ")}.`,rows:parsed.data.length,valid:[],invalid:[]};const fatal=parsed.errors.find(error=>error.type==="Quotes"||error.code==="UndetectableDelimiter");if(fatal)return{error:fatal.message,rows:parsed.data.length,valid:[],invalid:[]};const valid=[],invalid=[];parsed.data.forEach((row,index)=>{const result=convert(row);if(result.success)valid.push(result.data);else invalid.push({rowNumber:index+2,error:result.error?.issues?.[0]?.message??result.error??"Invalid row."});});return{rows:parsed.data.length,valid,invalid,parseWarnings:parsed.errors.length};};
const matchName=(name,items)=>{const matches=items.filter(item=>item.name.toLowerCase()===String(name??"").trim().toLowerCase());return matches.length===1?matches[0]:null;};
export const parseTransferCsv=(text,accounts,createId=()=>crypto.randomUUID())=>parse(text,["from account","to account","amount","date"],row=>{const from=matchName(row["from account"],getAllAccounts(accounts)),to=matchName(row["to account"],getAllAccounts(accounts));if(!from||!to)return{success:false,error:"Unknown or ambiguous account."};return validateTransferInput({id:`transfer-${createId()}`,fromAccountId:from.id,toAccountId:to.id,amount:row.amount,date:row.date,note:row.note??"",createdAt:new Date().toISOString()});});
export const parseAccountCsv=(text,createId=()=>crypto.randomUUID())=>parse(text,["name","type","opening balance"],row=>validateAccountInput({id:`account-${createId()}`,name:row.name,type:row.type,openingBalance:row["opening balance"],archived:boolean(row.archived),createdAt:new Date().toISOString()}));
export const parseCustomCategoryCsv=(text,createId=()=>crypto.randomUUID())=>{const names=new Set([...builtInCategories,...mainCategories].map(item=>item.name.toLocaleLowerCase()));return parse(text,["name","type","icon"],row=>{const name=String(row.name??"").trim().toLocaleLowerCase();if(names.has(name))return{success:false,error:"Category name duplicates a built-in or earlier CSV category."};const mainInput=String(row["main category"]||"").trim().toLowerCase(),main=mainCategories.find(item=>item.id===mainInput||item.name.toLowerCase()===mainInput),iconType=String(row["icon type"]||"emoji").trim().toLowerCase();const result=validateCustomCategory({id:`custom-${createId()}`,name:row.name,type:row.type,mainCategoryId:main?.id||(String(row.type).toLowerCase()==="income"?"income":"other"),iconType,imageData:String(row["image data"]||"").trim()||null,icon:row.icon,keywords:String(row.keywords??"").split(";").map(value=>value.trim()).filter(Boolean),budgetGroup:row["50/30/20 classification"]||null,archived:boolean(row.archived),createdAt:new Date().toISOString()});if(result.success)names.add(name);return result;});};
export const parseSavingsGoalCsv=(text,accounts,createId=()=>crypto.randomUUID())=>parse(text,["name","target amount"],row=>{const linked=String(row["linked account"]??"").trim()?matchName(row["linked account"],getAllAccounts(accounts)):null;if(String(row["linked account"]??"").trim()&&!linked)return{success:false,error:"Unknown or ambiguous linked account."};return validateSavingsGoalInput({id:`goal-${createId()}`,name:row.name,targetAmount:row["target amount"],targetDate:row["target date"],linkedAccountId:linked?.id,icon:row.icon||GOAL_ICONS[0],note:row.note??"",archived:boolean(row.archived),createdAt:new Date().toISOString()});});
export const parseGoalContributionCsv=(text,goals,accounts,createId=()=>crypto.randomUUID())=>parse(text,["goal","amount","date","account"],row=>{const goal=matchName(row.goal,goals),account=matchName(row.account,getAllAccounts(accounts));if(!goal||!account)return{success:false,error:"Unknown or ambiguous goal/account."};return validateSavingsGoalContributionInput({id:`goal-contribution-${createId()}`,goalId:goal.id,amount:row.amount,date:row.date,accountId:account.id,note:row.note??"",createdAt:new Date().toISOString()});});

