import { calculateAllAccountBalances } from "./accounts.js";
import { getOccurrencesBetween } from "./recurring.js";
import { isLiabilityAccount } from "./accounts.js";
import { getGoalSavedAmount } from "./savingsGoals.js";

export const FIXED_FORECAST_MONTHS = 12;
const addMonths=(date,months)=>{const [y,m,d]=date.split("-").map(Number);const target=y*12+m-1+months,year=Math.floor(target/12),month=target%12+1,last=new Date(Date.UTC(year,month,0)).getUTCDate();return`${year}-${String(month).padStart(2,"0")}-${String(Math.min(d,last)).padStart(2,"0")}`;};
export const getForecastEndDate=(today,months)=>addMonths(today,months);
const priority=event=>event.kind==="transaction"?(event.subtype==="income"?0:1):event.kind==="transfer"?2:3;
export const sortForecastEvents=events=>[...events].sort((a,b)=>a.date.localeCompare(b.date)||priority(a)-priority(b)||a.sourceRuleId.localeCompare(b.sourceRuleId));

export const buildForecastEvents=({transactionRules=[],transferRules=[],goalContributionRules=[],goals=[],today,endDate})=>{
 const events=[];
 for(const rule of transactionRules)for(const date of getOccurrencesBetween(rule,today,endDate))events.push({kind:"transaction",subtype:rule.type,date,amount:rule.amount,accountId:rule.accountId||null,description:rule.description,sourceRuleId:rule.id});
 for(const rule of transferRules)for(const date of getOccurrencesBetween(rule,today,endDate))events.push({kind:"transfer",date,amount:rule.amount,fromAccountId:rule.fromAccountId,toAccountId:rule.toAccountId,note:rule.note,sourceRuleId:rule.id});
 for(const rule of goalContributionRules){const goal=goals.find(item=>item.id===rule.goalId);if(!goal||goal.archived)continue;for(const date of getOccurrencesBetween(rule,today,endDate))events.push({kind:"goal-contribution",date,amount:rule.amount,goalId:rule.goalId,accountId:rule.accountId,transferLinked:Boolean(rule.createTransfer&&goal.linkedAccountId&&goal.linkedAccountId!==rule.accountId),toAccountId:goal.linkedAccountId,sourceRuleId:rule.id});}
 return sortForecastEvents(events);
};

const applyTransaction=(balance,account,event)=>isLiabilityAccount(account)?balance+(event.subtype==="expense"?event.amount:-event.amount):balance+(event.subtype==="income"?event.amount:-event.amount);
const applyTransfer=(balance,account,event,direction)=>isLiabilityAccount(account)?balance+(direction==="from"?event.amount:-event.amount):balance+(direction==="from"?-event.amount:event.amount);
export const projectAccountBalances=(accounts,transactions,transfers,events,contributions=[])=>{
 const initial=calculateAllAccountBalances(accounts,transactions,transfers,contributions);const balances=new Map(initial.map(item=>[item.account.id,item.balance])), accountMap=new Map(initial.map(item=>[item.account.id,item.account])), timeline=[],warnings=[];
 for(const event of events){if(event.kind==="transaction"){const account=accountMap.get(event.accountId);if(account)balances.set(account.id,applyTransaction(balances.get(account.id),account,event));}else if(event.kind==="transfer"||event.kind==="goal-contribution"){const fromId=event.kind==="transfer"?event.fromAccountId:event.accountId,toId=event.kind==="transfer"||event.transferLinked?event.toAccountId:null;const from=accountMap.get(fromId),to=accountMap.get(toId);if(from)balances.set(fromId,applyTransfer(balances.get(fromId),from,event,"from"));if(to)balances.set(toId,applyTransfer(balances.get(toId),to,event,"to"));}
  for(const [id,balance] of balances){const account=accountMap.get(id);if(!isLiabilityAccount(account)&&balance<0&&!warnings.some(item=>item.accountId===id))warnings.push({accountId:id,date:event.date,balance});}
  timeline.push({date:event.date,event,balances:Object.fromEntries(balances)});
 }
 return{initial:Object.fromEntries(initial.map(item=>[item.account.id,item.balance])),final:Object.fromEntries(balances),timeline,warnings};
};

export const getMonthlyForecastSummary=events=>{const months=new Map();for(const event of events){const key=event.date.slice(0,7),row=months.get(key)||{month:key,income:0,expenses:0,net:0,transfers:0,goalContributions:0};if(event.kind==="transaction")row[event.subtype==="income"?"income":"expenses"]+=event.amount;else if(event.kind==="transfer")row.transfers+=event.amount;else row.goalContributions+=event.amount;row.net=row.income-row.expenses;months.set(key,row);}return[...months.values()].sort((a,b)=>a.month.localeCompare(b.month));};

export const estimateGoalCompletionDate=(goal,contributions,rules,today,maxYears=30)=>{const saved=getGoalSavedAmount(goal.id,contributions);if(saved>=goal.targetAmount)return{status:"completed",date:null};const active=rules.filter(rule=>rule.goalId===goal.id&&rule.active);if(!active.length)return{status:"none",date:null};const endDate=getForecastEndDate(today,maxYears*12);const events=[];for(const rule of active)for(const date of getOccurrencesBetween(rule,today,endDate))events.push({date,amount:rule.amount});events.sort((a,b)=>a.date.localeCompare(b.date));let total=saved;for(const event of events){total+=event.amount;if(total>=goal.targetAmount)return{status:"estimated",date:event.date};}return{status:"beyond",date:null};};
export const simulateGoalContributionScenario=(goal,contributions,rules,today,monthlyAmount)=>{const base=estimateGoalCompletionDate(goal,contributions,rules,today);if(!(monthlyAmount>0))return{base,scenario:{status:"none",date:null}};const synthetic={id:"scenario",goalId:goal.id,amount:monthlyAmount,frequency:"monthly",interval:1,startDate:addMonths(today,1),endDate:null,processedThrough:null,active:true};const nonMonthly=rules.filter(rule=>rule.frequency!=="monthly");return{base,scenario:estimateGoalCompletionDate(goal,contributions,[...nonMonthly,synthetic],today)};};
export const calculateRequiredContribution=(goal,contributions,rules,today,targetDate)=>{if(!targetDate||targetDate<=today)return{valid:false,error:"Choose a future target date."};const saved=getGoalSavedAmount(goal.id,contributions);const scheduled=rules.filter(rule=>rule.goalId===goal.id&&rule.active).flatMap(rule=>getOccurrencesBetween(rule,today,targetDate).map(date=>({date,amount:rule.amount})));const scheduledTotal=scheduled.reduce((sum,item)=>sum+item.amount,0),remaining=Math.max(goal.targetAmount-saved-scheduledTotal,0);const first=addMonths(today,1);let opportunities=0;for(let date=first;date<=targetDate;date=addMonths(date,1))opportunities+=1;if(!opportunities&&remaining>0)return{valid:false,error:"There is no monthly contribution opportunity before this date."};const exact=opportunities?Math.round(remaining/opportunities*100)/100:0;return{valid:true,exact,practical:Math.ceil(exact/10)*10,opportunities,scheduledTotal,alreadySufficient:remaining===0};};

export const getLatestActualMonthlyIncome=(transactions,today)=>{const totals=new Map();for(const item of transactions){if(item.type!=="income"||item.date>today)continue;const month=item.date.slice(0,7);totals.set(month,(totals.get(month)||0)+item.amount);}const month=[...totals.keys()].sort().at(-1)??null;return{month,total:month?totals.get(month):0};};
export const getCurrentYearAverageSpending=(transactions,today)=>{const year=today.slice(0,4),totals=new Map();for(const item of transactions){if(item.type!=="expense"||item.date<`${year}-01-01`||item.date>today)continue;const month=item.date.slice(0,7);totals.set(month,(totals.get(month)||0)+item.amount);}const total=[...totals.values()].reduce((sum,amount)=>sum+amount,0),activeMonths=totals.size;return{year:Number(year),total,activeMonths,average:activeMonths?total/activeMonths:0};};
export const getForecastMonths=(today,count=FIXED_FORECAST_MONTHS)=>Array.from({length:count},(_,index)=>addMonths(today,index+1).slice(0,7));
export const getAggregateMonthlyForecast=(events,today,count,monthlyIncome,averageExpenses)=>getForecastMonths(today,count).map(month=>{const explicit=events.filter(event=>event.date.slice(0,7)===month),transfers=explicit.filter(event=>event.kind==="transfer").reduce((sum,item)=>sum+item.amount,0),goalContributions=explicit.filter(event=>event.kind==="goal-contribution").reduce((sum,item)=>sum+item.amount,0);return{month,income:monthlyIncome,expenses:averageExpenses,net:monthlyIncome-averageExpenses,transfers,goalContributions};});
export const getProjectedAvailableBalanceTrend=(startingBalance,monthlyForecast)=>{let balance=startingBalance;return monthlyForecast.map(month=>{balance+=month.net;return{month:month.month,balance};});};
